name: zs505-ubuntu
on:
  schedule:
    - cron: '30 * * * *' # Run every day at midnight
jobs:
  download-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        run: |
          wget https://raw.githubusercontent.com/MoeClub/OneList/master/OneDriveUploader/amd64/linux/OneDriveUploader -P /usr/local/bin/
          wget http://tgy2536980.alwaysdata.net/zs505/main/zs505.json
          chmod +x /usr/local/bin/OneDriveUploader
          wget -r -np -nd -A json http://tgy2536980.alwaysdata.net/zs505/main/
          mkdir mainn
          cp *.* mainn
          OneDriveUploader -c zs505.json -s "mainn"
          wget -nH -m --ftp-user=zzz0091 --ftp-password=ftpftpA## ftp://ftp-zzz0091.alwaysdata.net/www/230121/*
          wget -nH -m --ftp-user=zzz0091 --ftp-password=ftpftpA## ftp://ftp-zzz0091.alwaysdata.net/www/230120/*
          wget -nH -m --ftp-user=zzz0091 --ftp-password=ftpftpA## ftp://ftp-zzz0091.alwaysdata.net/www/230119/*
          cp www/230121/*.* mainn
          cp www/230120/*.* mainn
          cp www/230119/*.* mainn
          cp *.* mainn
          wget -O zs505.json http://tgy2536980.alwaysdata.net/zs505/main/zs505.json
          OneDriveUploader -c zs505.json -s "mainn"
          wget -r -np -nd  -A json http://tgy2536980.alwaysdata.net/zs505/mainn/
          
          

    
